"""
Django settings for idp_provider project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from .config import *


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4$qo1tbsp01&tmp9bn+$mtas9&=eo23yjf+x4d*p*t99f9$ogz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
] + APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'idp_provider.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'idp_provider.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'core' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

AUTH_USER_MODEL = 'users.User'

# Site framework
SITE_ID = 1

# django-allauth configuration
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_LOGOUT_ON_GET = True

# Social Account (Google OAuth2) configuration
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,
            'key': '',
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',
        },
    }
}

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# SAML IdP Configuration
SAML_IDP_CONFIG = {
    'xmlsec_binary': '/usr/bin/xmlsec1',  # Path to xmlsec1 binary
    
    'entityid': 'http://localhost:8000/saml2/idp/metadata/',
    
    'port': 8000,
    
    'service': {
        'idp': {
            'name': 'Django SAML IdP',
            'endpoints': {
                'single_sign_on_service': [
                    ('http://localhost:8000/saml2/idp/sso/post', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'),
                    ('http://localhost:8000/saml2/idp/sso/redirect', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'),
                ],
                'single_logout_service': [
                    ('http://localhost:8000/saml2/idp/slo/post', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'),
                    ('http://localhost:8000/saml2/idp/slo/redirect', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'),
                ],
            },
            'policy': {
                'default': {
                    'lifetime': {'minutes': 15},
                    'attribute_restrictions': None,
                    'name_form': 'urn:oasis:names:tc:SAML:2.0:attrname-format:uri',
                },
            },
            'subject_data_lifetime': {'minutes': 30},
        },
    },
    
    # Certificate and key for signing SAML responses
    'key_file': BASE_DIR / 'certificates/idp_private_key.pem',
    'cert_file': BASE_DIR / 'certificates/idp_public_cert.pem',
    
    # Metadata
    'metadata': {
        'local': [BASE_DIR / 'idp_provider/metadata.xml'],
    },
}

# djangosaml2idp specific settings
SAML_CONFIG = SAML_IDP_CONFIG

# Login URL for SAML authentication
LOGIN_URL = '/accounts/login/'

# Where to redirect after login
LOGIN_REDIRECT_URL = '/'

# Attribute mapping - map Django user attributes to SAML attributes
SAML_ATTRIBUTE_MAPPING = {
    'email': ['email', 'urn:oid:0.9.2342.19200300.100.1.3'],
    'username': ['username', 'urn:oid:0.9.2342.19200300.100.1.1'],
    'first_name': ['first_name', 'urn:oid:2.5.4.42'],
    'last_name': ['last_name', 'urn:oid:2.5.4.4'],
}

# SAML Attribute Processors
# These functions extract and transform user attributes for SAML assertions
SAML_ATTRIBUTE_PROCESSORS = {
    'core.saml_processors.user_attributes',  # Default processor
    # Add more processors as needed:
    # 'core.saml_processors.user_full_info',
}

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')